// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	eriaconsumer "github.com/project-eria/eria-core/consumer"
	mock "github.com/stretchr/testify/mock"
)

// PropertyOption is an autogenerated mock type for the PropertyOption type
type PropertyOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *PropertyOption) Execute(_a0 *eriaconsumer.EriaProperty) {
	_m.Called(_a0)
}

// NewPropertyOption creates a new instance of PropertyOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPropertyOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *PropertyOption {
	mock := &PropertyOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
