// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	eriaconsumer "github.com/project-eria/eria-core/consumer"
	mock "github.com/stretchr/testify/mock"
)

// ThingOption is an autogenerated mock type for the ThingOption type
type ThingOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ThingOption) Execute(_a0 *eriaconsumer.EriaThing) {
	_m.Called(_a0)
}

// NewThingOption creates a new instance of ThingOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThingOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThingOption {
	mock := &ThingOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
